### ISSUE TITLE
Proposal to Increase Maximum Validator Count

### ISSUE THREAD

**Issue by kritarth1107** [airchains-network/Airchains-Governance#2]
## Summary
This proposal suggests increasing the maximum number of validators in our network. The objective is to provide more community members the opportunity to participate actively, thereby enhancing the network's security, decentralization, and overall robustness.

## Background
Our community has shown significant interest in contributing to the network by running nodes. However, the current limit on the number of validators restricts their ability to participate fully. By increasing the validator count, we can accommodate more contributors, leveraging their enthusiasm and technical skills for the benefit of the network. This move aligns with our goals of promoting inclusivity and strengthening our network infrastructure.

## Objective
- **Increase Participation:** Increase the maximum validator count to allow more community members to participate as validators.
- **Enhance Security:** Enhance the network's security by distributing validation responsibilities across a larger number of nodes.
- **Promote Decentralization:** Strengthen the network's decentralization to reduce risks of centralization and enhance trust among participants.

## Justification
1. **Community Engagement:**
   - There is a notable demand from community members who are eager to become validators.
   - Expanding the validator set will harness this interest and promote greater engagement and involvement in the network's operations.

2. **Network Security:**
   - A larger validator set will contribute to the overall security and resilience of the network by distributing validation responsibilities more broadly.
   - Increased participation helps in preventing potential attacks and improves fault tolerance.

3. **Decentralization:**
   - Increasing the number of validators will further decentralize the network.
   - This move will reduce the risk of centralization, making the network more resilient to single points of failure and enhancing overall trust in the system.

## Considerations
1. **Technical Feasibility:**
   - Assess the impact on network performance, including latency, throughput, and consensus efficiency.
   - Identify any necessary changes to the protocol to support an increased number of validators without compromising performance.

2. **Stakeholder Feedback:**
   - Solicit input from community members, developers, and other stakeholders to ensure broad support.
   - Address any concerns or suggestions raised during the feedback process to refine the proposal.

## Proposed Actions
1. **Community Consultation:**
   - Initiate a discussion with the community through forums, social media, and other communication channels to gather feedback and gauge support for the proposal.
   - Document the feedback received and incorporate it into the proposal as needed.

2. **Feasibility Study:**
   - Conduct a technical feasibility study to understand the implications of increasing the validator count on network performance and security.
   - Perform an economic analysis to assess the impact on the reward structure and overall economic model.

3. **Implementation Plan:**
   - Develop a detailed implementation plan based on the findings of the feasibility study and community feedback.
   - Outline the steps required to increase the validator count, including any protocol changes, testing, and deployment strategies.

4. **Execution:**
   - Implement the changes to increase the validator count in a phased and controlled manner.
   - Monitor the impact on the network, including performance metrics and community feedback, to ensure the changes are beneficial and make adjustments as necessary.

## Conclusion
Increasing the maximum validator count will empower more community members to contribute actively, enhancing the network's security and decentralization. This proposal seeks to gather support and input from the community to move forward with this initiative, ensuring that the changes align with our collective goals and vision for the network.

**Comment by Adamtruong6868** [comment]
What is the maximum number? Does it means unlimited? i think around 125-150, but need someone have good experience of managing nodes. 
NO NEED to consider one team one node, as we are at the testnet. Decentralization is not yet the key, but good experience of noders are more important.
Too much validators, with low experience will not bring the value for testnet, but bring more problems.

**Comment by ComputerKeeda** [comment]
> What is the maximum number? Does it means unlimited? i think around 125-150, but need someone have good experience of managing nodes.
> NO NEED to consider one team one node, as we are at the testnet. Decentralization is not yet the key, but good experience of noders are more important.
> Too much validators, with low experience will not bring the value for testnet, but bring more problems.

We haven't decided on a specific maximum number yet. This proposal is aimed at gauging community interest and gathering feedback to determine an appropriate number. We agree that quality and experience of node operators are crucial during the testnet phase, rather than decentralization. The suggestion of 125-150 validators seems reasonable and aligns with our goal of enhancing network stability and security. This is just a proposal; if the majority disagrees, we will not proceed with it.

**Comment by john839361** [comment]
In my opinion, increase the number of Validators to 200. People who are not selected are very sad these past few days

**Comment by dra125259** [comment]
i think so john839361  increase the number of Validators to 200.

**Comment by dhe23115** [comment]
ok 200 validators

**Comment by flysky000999** [comment]
In my opinion, increase the number of Validators to 250

**Comment by vkvk12345612** [comment]
Devs consider increasing the number to 300 Validators. If everyone fails 100 Validators but the Node is still operating, they deserve to be chosen.

**Comment by lebaphuocthanh** [comment]
me too ,i thnk same vkvk12345612   Devs consider increasing the number to 300 Validators. If everyone fails 100 Validators but the Node is still operating, they deserve to be chosen

**Comment by napelvs** [comment]
In my opinion, the maximum validator number should not exceed 180. As far as I'm aware that's the largest number of validators a cometbft chain runs at. Even 180 is too much ... 100 is ideal already but considering there's more validators wanting to join the active set, I would set it at a max of 150.

**Comment by CoinHuntersTR** [comment]
Increasing the number of validators is a positive approach for the community. However, the number of validators should be limited to 150 or 200. Otherwise, it will be very difficult for the network to work stably.

**Comment by 0xChicharito** [comment]
i agree

**Comment by a3165458** [comment]
agree with you

**Comment by konsortech** [comment]
i think 100 max validator that was ideal for cosmos sdk in mainnet.
but we are still in testnet, we can go over 100.

**Comment by HarmonyNode** [comment]
200 validators is ok
